###用户
###注册
POST http://localhost:8080/user/sign-up/
Content-Type: application/json

{
    "password": "test111",
    "user_name": "小小展玮",
    "role": "1"
}

###登录
GET http://localhost:8080/user/login?user_name=小小展玮&password=test


###修改密码
PUT http://localhost:8080/user/updatepswd/
Content-Type: application/json

{
    "user_name": "小小展玮",
    "password": "test111",
    "new_password": "test"
}

###修改用户名
PUT http://localhost:8080/user/updatename?old_name=大大展玮&new_name=小小展玮

###修改角色
PUT http://localhost:8080/user/updaterole?&user_name=小小展玮&new_role=1

###注销账户（删除）
PUT http://localhost:8080/user/delete/
Content-Type: application/json

{
    "password": "test",
    "user_name": "小小展玮",
    "role": "1"
}


###课程
###添加课程
PUT http://localhost:8080/course/add?user_name=小小展玮&course_name=数据结构

###删除课程
PUT http://localhost:8080/course/delete?user_name=小小展玮&course_name=数据结构