
POST http://localhost:8080/user/sign-up/
Content-Type: application/json

{
    "Password": "test123",
    "UserName": "小小展玮",
    "Role": "1"
}

###
PUT http://localhost:8080/user/updatepswd/
Content-Type: application/json

{
    "Password": "test",
    "UserName": "小小展玮",
    "Role": "1",
    "NewPassword": "test123"
}